baseURL = '/'
locale = 'en-us'
title = 'Arthagaman'
theme = "PaperMod"

# This replaces the old paginate command perfectly!
[pagination]
    pagerSize = 5

[params]
    description = "Discovering the Soul of India"
    defaultTheme = "auto"

    # Keeps all posts in clean, uniform boxes
    DisableSpecialLargeFeatured = true
    CoverOpts.card = true

    # Keep this off so we can create a custom landing page in Step 2!
    [params.profileMode]
        enabled = false

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 5

    #test

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10
