name: Daily Automated Build

on:
  schedule:
    # Runs at 05:35 AM UTC (which is 11:05 AM IST)
    - cron: '35 5 * * *'
  workflow_dispatch: # Allows you to manually click a button to build anytime!

# Granting write permissions so GitHub can push the ping file
permissions:
  contents: write

jobs:
  ping-cloudflare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make a small change and push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          date > ping.txt
          git add ping.txt
          git commit -m "Automated Ping for Scheduled Posts" || exit 0
          git push
